In [12]:
#script for masterthesis 

import numpy as np
import pandas as pd
from sklearn.tree import DecisionTreeClassifier
from sklearn.ensemble import RandomForestClassifier
from sklearn.neighbors import KNeighborsClassifier


from sklearn.feature_selection import VarianceThreshold
from sklearn.model_selection import GridSearchCV
from sklearn.model_selection import train_test_split
from sklearn.metrics import confusion_matrix


In [13]:
#load dataset
dataset_import = pd.read_csv(r'/Users/danielsaffertmuller/Documents/Gesundheits- und Rehabilitationstechnik /Masterarbeit/Cereneo/dataprocessing/matlab_functions/Features_prod_IMU_v3.0.csv')
dataset = np.array(dataset_import)

In [14]:
#show shape of dataset
print(f'Shape of Dataset{dataset.shape}')

Shape of Dataset(2964, 44)


In [15]:
#show shape of features
x=dataset[:,:42]
print(f'Shape of Features{x.shape}')

Shape of Features(2964, 42)


In [16]:
#show shape of class
y=dataset[:,42]
print(f'Shape of class{y.shape}')
print(f'class{y}')

Shape of class(2964,)
class[1. 1. 1. ... 4. 4. 4.]


In [22]:
##random forest hyper parameter
class_weight = ["balanced", "balanced_subsample"]
n_trees = [10, 20, 30, 40 , 50, 60, 70, 80, 90, 100, 110, 120, 130, 140, 150, 160, 170, 180, 190, 200]
for i in range(1,57):
    for j in range(5,11):
        for k in range (0,1):
             for p in range (10,20):
                clf = RandomForestClassifier(max_features=i,max_depth=j,class_weight=class_weight[k], n_estimators=n_trees[p])
                clf.fit(x_train, y_train)
                score= clf.score(x_test, y_test)
                y_pred=clf.predict(x_test)
              
                print(f'score decision hyperparameter {class_weight[k]} {i} features and {j} depth {n_trees[p]} number of trees :  {score}')
    

score decision hyperparameter balanced 1 features and 5 depth 110 number of trees :  0.9184935356942102
score decision hyperparameter balanced 1 features and 5 depth 120 number of trees :  0.924114671163575
score decision hyperparameter balanced 1 features and 5 depth 130 number of trees :  0.9207419898819561
score decision hyperparameter balanced 1 features and 5 depth 140 number of trees :  0.9218662169758292
score decision hyperparameter balanced 1 features and 5 depth 150 number of trees :  0.9151208544125914
score decision hyperparameter balanced 1 features and 5 depth 160 number of trees :  0.9196177627880832
score decision hyperparameter balanced 1 features and 5 depth 170 number of trees :  0.9179314221472737
score decision hyperparameter balanced 1 features and 5 depth 180 number of trees :  0.9190556492411467
score decision hyperparameter balanced 1 features and 5 depth 190 number of trees :  0.9207419898819561
score decision hyperparameter balanced 1 features and 5 depth 200

score decision hyperparameter balanced 2 features and 6 depth 200 number of trees :  0.9443507588532883
score decision hyperparameter balanced 2 features and 7 depth 110 number of trees :  0.9567172568858909
score decision hyperparameter balanced 2 features and 7 depth 120 number of trees :  0.9561551433389545
score decision hyperparameter balanced 2 features and 7 depth 130 number of trees :  0.9539066891512086
score decision hyperparameter balanced 2 features and 7 depth 140 number of trees :  0.9578414839797639
score decision hyperparameter balanced 2 features and 7 depth 150 number of trees :  0.9550309162450815
score decision hyperparameter balanced 2 features and 7 depth 160 number of trees :  0.954468802698145
score decision hyperparameter balanced 2 features and 7 depth 170 number of trees :  0.9572793704328274
score decision hyperparameter balanced 2 features and 7 depth 180 number of trees :  0.954468802698145
score decision hyperparameter balanced 2 features and 7 depth 190 

score decision hyperparameter balanced 3 features and 8 depth 190 number of trees :  0.9623383923552558
score decision hyperparameter balanced 3 features and 8 depth 200 number of trees :  0.9578414839797639
score decision hyperparameter balanced 3 features and 9 depth 110 number of trees :  0.9629005059021922
score decision hyperparameter balanced 3 features and 9 depth 120 number of trees :  0.9623383923552558
score decision hyperparameter balanced 3 features and 9 depth 130 number of trees :  0.9629005059021922
score decision hyperparameter balanced 3 features and 9 depth 140 number of trees :  0.9612141652613828
score decision hyperparameter balanced 3 features and 9 depth 150 number of trees :  0.9606520517144463
score decision hyperparameter balanced 3 features and 9 depth 160 number of trees :  0.9617762788083193
score decision hyperparameter balanced 3 features and 9 depth 170 number of trees :  0.9623383923552558
score decision hyperparameter balanced 3 features and 9 depth 18

score decision hyperparameter balanced 4 features and 10 depth 180 number of trees :  0.9629005059021922
score decision hyperparameter balanced 4 features and 10 depth 190 number of trees :  0.9606520517144463
score decision hyperparameter balanced 4 features and 10 depth 200 number of trees :  0.9629005059021922
score decision hyperparameter balanced 5 features and 5 depth 110 number of trees :  0.927487352445194
score decision hyperparameter balanced 5 features and 5 depth 120 number of trees :  0.9319842608206858
score decision hyperparameter balanced 5 features and 5 depth 130 number of trees :  0.9297358066329399
score decision hyperparameter balanced 5 features and 5 depth 140 number of trees :  0.9280494659921305
score decision hyperparameter balanced 5 features and 5 depth 150 number of trees :  0.9325463743676222
score decision hyperparameter balanced 5 features and 5 depth 160 number of trees :  0.9286115795390669
score decision hyperparameter balanced 5 features and 5 depth 

score decision hyperparameter balanced 6 features and 6 depth 170 number of trees :  0.9437886453063519
score decision hyperparameter balanced 6 features and 6 depth 180 number of trees :  0.9432265317594154
score decision hyperparameter balanced 6 features and 6 depth 190 number of trees :  0.9460370994940978
score decision hyperparameter balanced 6 features and 6 depth 200 number of trees :  0.9449128724002248
score decision hyperparameter balanced 6 features and 7 depth 110 number of trees :  0.9584035975267003
score decision hyperparameter balanced 6 features and 7 depth 120 number of trees :  0.9572793704328274
score decision hyperparameter balanced 6 features and 7 depth 130 number of trees :  0.954468802698145
score decision hyperparameter balanced 6 features and 7 depth 140 number of trees :  0.9589657110736369
score decision hyperparameter balanced 6 features and 7 depth 150 number of trees :  0.9572793704328274
score decision hyperparameter balanced 6 features and 7 depth 160

score decision hyperparameter balanced 7 features and 8 depth 160 number of trees :  0.9612141652613828
score decision hyperparameter balanced 7 features and 8 depth 170 number of trees :  0.9600899381675099
score decision hyperparameter balanced 7 features and 8 depth 180 number of trees :  0.9606520517144463
score decision hyperparameter balanced 7 features and 8 depth 190 number of trees :  0.9640247329960652
score decision hyperparameter balanced 7 features and 8 depth 200 number of trees :  0.9606520517144463
score decision hyperparameter balanced 7 features and 9 depth 110 number of trees :  0.9612141652613828
score decision hyperparameter balanced 7 features and 9 depth 120 number of trees :  0.9600899381675099
score decision hyperparameter balanced 7 features and 9 depth 130 number of trees :  0.9578414839797639
score decision hyperparameter balanced 7 features and 9 depth 140 number of trees :  0.9623383923552558
score decision hyperparameter balanced 7 features and 9 depth 15

score decision hyperparameter balanced 8 features and 10 depth 150 number of trees :  0.9595278246205734
score decision hyperparameter balanced 8 features and 10 depth 160 number of trees :  0.9595278246205734
score decision hyperparameter balanced 8 features and 10 depth 170 number of trees :  0.9612141652613828
score decision hyperparameter balanced 8 features and 10 depth 180 number of trees :  0.9567172568858909
score decision hyperparameter balanced 8 features and 10 depth 190 number of trees :  0.9600899381675099
score decision hyperparameter balanced 8 features and 10 depth 200 number of trees :  0.9612141652613828
score decision hyperparameter balanced 9 features and 5 depth 110 number of trees :  0.9263631253513209
score decision hyperparameter balanced 9 features and 5 depth 120 number of trees :  0.9286115795390669
score decision hyperparameter balanced 9 features and 5 depth 130 number of trees :  0.927487352445194
score decision hyperparameter balanced 9 features and 5 dep

score decision hyperparameter balanced 10 features and 6 depth 140 number of trees :  0.9421023046655425
score decision hyperparameter balanced 10 features and 6 depth 150 number of trees :  0.9449128724002248
score decision hyperparameter balanced 10 features and 6 depth 160 number of trees :  0.9421023046655425
score decision hyperparameter balanced 10 features and 6 depth 170 number of trees :  0.9409780775716695
score decision hyperparameter balanced 10 features and 6 depth 180 number of trees :  0.941540191118606
score decision hyperparameter balanced 10 features and 6 depth 190 number of trees :  0.9359190556492412
score decision hyperparameter balanced 10 features and 6 depth 200 number of trees :  0.9398538504777965
score decision hyperparameter balanced 10 features and 7 depth 110 number of trees :  0.9527824620573356
score decision hyperparameter balanced 10 features and 7 depth 120 number of trees :  0.954468802698145
score decision hyperparameter balanced 10 features and 7 

score decision hyperparameter balanced 11 features and 8 depth 130 number of trees :  0.9550309162450815
score decision hyperparameter balanced 11 features and 8 depth 140 number of trees :  0.955593029792018
score decision hyperparameter balanced 11 features and 8 depth 150 number of trees :  0.954468802698145
score decision hyperparameter balanced 11 features and 8 depth 160 number of trees :  0.9567172568858909
score decision hyperparameter balanced 11 features and 8 depth 170 number of trees :  0.9539066891512086
score decision hyperparameter balanced 11 features and 8 depth 180 number of trees :  0.955593029792018
score decision hyperparameter balanced 11 features and 8 depth 190 number of trees :  0.9561551433389545
score decision hyperparameter balanced 11 features and 8 depth 200 number of trees :  0.9539066891512086
score decision hyperparameter balanced 11 features and 9 depth 110 number of trees :  0.9567172568858909
score decision hyperparameter balanced 11 features and 9 d

score decision hyperparameter balanced 12 features and 10 depth 120 number of trees :  0.955593029792018
score decision hyperparameter balanced 12 features and 10 depth 130 number of trees :  0.9567172568858909
score decision hyperparameter balanced 12 features and 10 depth 140 number of trees :  0.9584035975267003
score decision hyperparameter balanced 12 features and 10 depth 150 number of trees :  0.954468802698145
score decision hyperparameter balanced 12 features and 10 depth 160 number of trees :  0.9533445756042721
score decision hyperparameter balanced 12 features and 10 depth 170 number of trees :  0.9561551433389545
score decision hyperparameter balanced 12 features and 10 depth 180 number of trees :  0.9550309162450815
score decision hyperparameter balanced 12 features and 10 depth 190 number of trees :  0.9561551433389545
score decision hyperparameter balanced 12 features and 10 depth 200 number of trees :  0.9572793704328274
score decision hyperparameter balanced 13 featur

score decision hyperparameter balanced 14 features and 6 depth 110 number of trees :  0.93929173693086
score decision hyperparameter balanced 14 features and 6 depth 120 number of trees :  0.9387296233839235
score decision hyperparameter balanced 14 features and 6 depth 130 number of trees :  0.9409780775716695
score decision hyperparameter balanced 14 features and 6 depth 140 number of trees :  0.9409780775716695
score decision hyperparameter balanced 14 features and 6 depth 150 number of trees :  0.9409780775716695
score decision hyperparameter balanced 14 features and 6 depth 160 number of trees :  0.9421023046655425
score decision hyperparameter balanced 14 features and 6 depth 170 number of trees :  0.9432265317594154
score decision hyperparameter balanced 14 features and 6 depth 180 number of trees :  0.940415964024733
score decision hyperparameter balanced 14 features and 6 depth 190 number of trees :  0.9398538504777965
score decision hyperparameter balanced 14 features and 6 d

score decision hyperparameter balanced 15 features and 7 depth 200 number of trees :  0.9488476672287802
score decision hyperparameter balanced 15 features and 8 depth 110 number of trees :  0.954468802698145
score decision hyperparameter balanced 15 features and 8 depth 120 number of trees :  0.9516582349634626
score decision hyperparameter balanced 15 features and 8 depth 130 number of trees :  0.9516582349634626
score decision hyperparameter balanced 15 features and 8 depth 140 number of trees :  0.9533445756042721
score decision hyperparameter balanced 15 features and 8 depth 150 number of trees :  0.9527824620573356
score decision hyperparameter balanced 15 features and 8 depth 160 number of trees :  0.9539066891512086
score decision hyperparameter balanced 15 features and 8 depth 170 number of trees :  0.955593029792018
score decision hyperparameter balanced 15 features and 8 depth 180 number of trees :  0.952220348510399
score decision hyperparameter balanced 15 features and 8 d

score decision hyperparameter balanced 16 features and 9 depth 190 number of trees :  0.9550309162450815
score decision hyperparameter balanced 16 features and 9 depth 200 number of trees :  0.954468802698145
score decision hyperparameter balanced 16 features and 10 depth 110 number of trees :  0.9499718943226532
score decision hyperparameter balanced 16 features and 10 depth 120 number of trees :  0.9539066891512086
score decision hyperparameter balanced 16 features and 10 depth 130 number of trees :  0.9539066891512086
score decision hyperparameter balanced 16 features and 10 depth 140 number of trees :  0.9533445756042721
score decision hyperparameter balanced 16 features and 10 depth 150 number of trees :  0.9510961214165261
score decision hyperparameter balanced 16 features and 10 depth 160 number of trees :  0.9527824620573356
score decision hyperparameter balanced 16 features and 10 depth 170 number of trees :  0.9527824620573356
score decision hyperparameter balanced 16 feature

score decision hyperparameter balanced 18 features and 5 depth 170 number of trees :  0.927487352445194
score decision hyperparameter balanced 18 features and 5 depth 180 number of trees :  0.9263631253513209
score decision hyperparameter balanced 18 features and 5 depth 190 number of trees :  0.9269252388982574
score decision hyperparameter balanced 18 features and 5 depth 200 number of trees :  0.9286115795390669
score decision hyperparameter balanced 18 features and 6 depth 110 number of trees :  0.9359190556492412
score decision hyperparameter balanced 18 features and 6 depth 120 number of trees :  0.938167509836987
score decision hyperparameter balanced 18 features and 6 depth 130 number of trees :  0.9387296233839235
score decision hyperparameter balanced 18 features and 6 depth 140 number of trees :  0.9376053962900506
score decision hyperparameter balanced 18 features and 6 depth 150 number of trees :  0.93929173693086
score decision hyperparameter balanced 18 features and 6 de

score decision hyperparameter balanced 19 features and 7 depth 160 number of trees :  0.9471613265879708
score decision hyperparameter balanced 19 features and 7 depth 170 number of trees :  0.9454749859471613
score decision hyperparameter balanced 19 features and 7 depth 180 number of trees :  0.9460370994940978
score decision hyperparameter balanced 19 features and 7 depth 190 number of trees :  0.9443507588532883
score decision hyperparameter balanced 19 features and 7 depth 200 number of trees :  0.9449128724002248
score decision hyperparameter balanced 19 features and 8 depth 110 number of trees :  0.9505340078695896
score decision hyperparameter balanced 19 features and 8 depth 120 number of trees :  0.9539066891512086
score decision hyperparameter balanced 19 features and 8 depth 130 number of trees :  0.9505340078695896
score decision hyperparameter balanced 19 features and 8 depth 140 number of trees :  0.9488476672287802
score decision hyperparameter balanced 19 features and 

score decision hyperparameter balanced 20 features and 9 depth 150 number of trees :  0.9527824620573356
score decision hyperparameter balanced 20 features and 9 depth 160 number of trees :  0.9550309162450815
score decision hyperparameter balanced 20 features and 9 depth 170 number of trees :  0.9527824620573356
score decision hyperparameter balanced 20 features and 9 depth 180 number of trees :  0.9533445756042721
score decision hyperparameter balanced 20 features and 9 depth 190 number of trees :  0.9516582349634626
score decision hyperparameter balanced 20 features and 9 depth 200 number of trees :  0.952220348510399
score decision hyperparameter balanced 20 features and 10 depth 110 number of trees :  0.9482855536818438
score decision hyperparameter balanced 20 features and 10 depth 120 number of trees :  0.952220348510399
score decision hyperparameter balanced 20 features and 10 depth 130 number of trees :  0.9510961214165261
score decision hyperparameter balanced 20 features and

score decision hyperparameter balanced 22 features and 5 depth 130 number of trees :  0.9302979201798763
score decision hyperparameter balanced 22 features and 5 depth 140 number of trees :  0.9280494659921305
score decision hyperparameter balanced 22 features and 5 depth 150 number of trees :  0.9269252388982574
score decision hyperparameter balanced 22 features and 5 depth 160 number of trees :  0.927487352445194
score decision hyperparameter balanced 22 features and 5 depth 170 number of trees :  0.9258010118043845
score decision hyperparameter balanced 22 features and 5 depth 180 number of trees :  0.9280494659921305
score decision hyperparameter balanced 22 features and 5 depth 190 number of trees :  0.9258010118043845
score decision hyperparameter balanced 22 features and 5 depth 200 number of trees :  0.9263631253513209
score decision hyperparameter balanced 22 features and 6 depth 110 number of trees :  0.9359190556492412
score decision hyperparameter balanced 22 features and 6

score decision hyperparameter balanced 23 features and 7 depth 120 number of trees :  0.9460370994940978
score decision hyperparameter balanced 23 features and 7 depth 130 number of trees :  0.9437886453063519
score decision hyperparameter balanced 23 features and 7 depth 140 number of trees :  0.9465992130410343
score decision hyperparameter balanced 23 features and 7 depth 150 number of trees :  0.9443507588532883
score decision hyperparameter balanced 23 features and 7 depth 160 number of trees :  0.9460370994940978
score decision hyperparameter balanced 23 features and 7 depth 170 number of trees :  0.9443507588532883
score decision hyperparameter balanced 23 features and 7 depth 180 number of trees :  0.9432265317594154
score decision hyperparameter balanced 23 features and 7 depth 190 number of trees :  0.9437886453063519
score decision hyperparameter balanced 23 features and 7 depth 200 number of trees :  0.941540191118606
score decision hyperparameter balanced 23 features and 8

score decision hyperparameter balanced 24 features and 9 depth 110 number of trees :  0.9505340078695896
score decision hyperparameter balanced 24 features and 9 depth 120 number of trees :  0.9443507588532883
score decision hyperparameter balanced 24 features and 9 depth 130 number of trees :  0.9533445756042721
score decision hyperparameter balanced 24 features and 9 depth 140 number of trees :  0.9499718943226532
score decision hyperparameter balanced 24 features and 9 depth 150 number of trees :  0.9510961214165261
score decision hyperparameter balanced 24 features and 9 depth 160 number of trees :  0.9499718943226532
score decision hyperparameter balanced 24 features and 9 depth 170 number of trees :  0.9505340078695896
score decision hyperparameter balanced 24 features and 9 depth 180 number of trees :  0.9499718943226532
score decision hyperparameter balanced 24 features and 9 depth 190 number of trees :  0.9527824620573356
score decision hyperparameter balanced 24 features and 

score decision hyperparameter balanced 25 features and 10 depth 190 number of trees :  0.9488476672287802
score decision hyperparameter balanced 25 features and 10 depth 200 number of trees :  0.9482855536818438
score decision hyperparameter balanced 26 features and 5 depth 110 number of trees :  0.927487352445194
score decision hyperparameter balanced 26 features and 5 depth 120 number of trees :  0.9269252388982574
score decision hyperparameter balanced 26 features and 5 depth 130 number of trees :  0.927487352445194
score decision hyperparameter balanced 26 features and 5 depth 140 number of trees :  0.9291736930860034
score decision hyperparameter balanced 26 features and 5 depth 150 number of trees :  0.9297358066329399
score decision hyperparameter balanced 26 features and 5 depth 160 number of trees :  0.9280494659921305
score decision hyperparameter balanced 26 features and 5 depth 170 number of trees :  0.925238898257448
score decision hyperparameter balanced 26 features and 5

score decision hyperparameter balanced 27 features and 6 depth 180 number of trees :  0.9359190556492412
score decision hyperparameter balanced 27 features and 6 depth 190 number of trees :  0.9347948285553682
score decision hyperparameter balanced 27 features and 6 depth 200 number of trees :  0.9353569421023047
score decision hyperparameter balanced 27 features and 7 depth 110 number of trees :  0.9426644182124789
score decision hyperparameter balanced 27 features and 7 depth 120 number of trees :  0.9426644182124789
score decision hyperparameter balanced 27 features and 7 depth 130 number of trees :  0.941540191118606
score decision hyperparameter balanced 27 features and 7 depth 140 number of trees :  0.9421023046655425
score decision hyperparameter balanced 27 features and 7 depth 150 number of trees :  0.9398538504777965
score decision hyperparameter balanced 27 features and 7 depth 160 number of trees :  0.9432265317594154
score decision hyperparameter balanced 27 features and 7

score decision hyperparameter balanced 28 features and 8 depth 160 number of trees :  0.9510961214165261
score decision hyperparameter balanced 28 features and 8 depth 170 number of trees :  0.9499718943226532
score decision hyperparameter balanced 28 features and 8 depth 180 number of trees :  0.9494097807757167
score decision hyperparameter balanced 28 features and 8 depth 190 number of trees :  0.952220348510399
score decision hyperparameter balanced 28 features and 8 depth 200 number of trees :  0.9505340078695896
score decision hyperparameter balanced 28 features and 9 depth 110 number of trees :  0.9505340078695896
score decision hyperparameter balanced 28 features and 9 depth 120 number of trees :  0.9533445756042721
score decision hyperparameter balanced 28 features and 9 depth 130 number of trees :  0.9516582349634626
score decision hyperparameter balanced 28 features and 9 depth 140 number of trees :  0.9477234401349073
score decision hyperparameter balanced 28 features and 9

score decision hyperparameter balanced 29 features and 10 depth 140 number of trees :  0.9499718943226532
score decision hyperparameter balanced 29 features and 10 depth 150 number of trees :  0.9499718943226532
score decision hyperparameter balanced 29 features and 10 depth 160 number of trees :  0.9505340078695896
score decision hyperparameter balanced 29 features and 10 depth 170 number of trees :  0.9471613265879708
score decision hyperparameter balanced 29 features and 10 depth 180 number of trees :  0.9471613265879708
score decision hyperparameter balanced 29 features and 10 depth 190 number of trees :  0.9482855536818438
score decision hyperparameter balanced 29 features and 10 depth 200 number of trees :  0.9488476672287802
score decision hyperparameter balanced 30 features and 5 depth 110 number of trees :  0.9263631253513209
score decision hyperparameter balanced 30 features and 5 depth 120 number of trees :  0.9302979201798763
score decision hyperparameter balanced 30 featur

score decision hyperparameter balanced 31 features and 6 depth 120 number of trees :  0.9364811691961776
score decision hyperparameter balanced 31 features and 6 depth 130 number of trees :  0.9336706014614953
score decision hyperparameter balanced 31 features and 6 depth 140 number of trees :  0.9353569421023047
score decision hyperparameter balanced 31 features and 6 depth 150 number of trees :  0.9364811691961776
score decision hyperparameter balanced 31 features and 6 depth 160 number of trees :  0.9359190556492412
score decision hyperparameter balanced 31 features and 6 depth 170 number of trees :  0.9347948285553682
score decision hyperparameter balanced 31 features and 6 depth 180 number of trees :  0.9364811691961776
score decision hyperparameter balanced 31 features and 6 depth 190 number of trees :  0.9347948285553682
score decision hyperparameter balanced 31 features and 6 depth 200 number of trees :  0.9342327150084317
score decision hyperparameter balanced 31 features and 

score decision hyperparameter balanced 32 features and 8 depth 110 number of trees :  0.9510961214165261
score decision hyperparameter balanced 32 features and 8 depth 120 number of trees :  0.9488476672287802
score decision hyperparameter balanced 32 features and 8 depth 130 number of trees :  0.9482855536818438
score decision hyperparameter balanced 32 features and 8 depth 140 number of trees :  0.9499718943226532
score decision hyperparameter balanced 32 features and 8 depth 150 number of trees :  0.9471613265879708
score decision hyperparameter balanced 32 features and 8 depth 160 number of trees :  0.9499718943226532
score decision hyperparameter balanced 32 features and 8 depth 170 number of trees :  0.9488476672287802
score decision hyperparameter balanced 32 features and 8 depth 180 number of trees :  0.9488476672287802
score decision hyperparameter balanced 32 features and 8 depth 190 number of trees :  0.9494097807757167
score decision hyperparameter balanced 32 features and 

score decision hyperparameter balanced 33 features and 9 depth 190 number of trees :  0.9477234401349073
score decision hyperparameter balanced 33 features and 9 depth 200 number of trees :  0.9505340078695896
score decision hyperparameter balanced 33 features and 10 depth 110 number of trees :  0.9477234401349073
score decision hyperparameter balanced 33 features and 10 depth 120 number of trees :  0.9488476672287802
score decision hyperparameter balanced 33 features and 10 depth 130 number of trees :  0.9471613265879708
score decision hyperparameter balanced 33 features and 10 depth 140 number of trees :  0.9454749859471613
score decision hyperparameter balanced 33 features and 10 depth 150 number of trees :  0.9482855536818438
score decision hyperparameter balanced 33 features and 10 depth 160 number of trees :  0.9505340078695896
score decision hyperparameter balanced 33 features and 10 depth 170 number of trees :  0.952220348510399
score decision hyperparameter balanced 33 feature

score decision hyperparameter balanced 35 features and 5 depth 170 number of trees :  0.9308600337268128
score decision hyperparameter balanced 35 features and 5 depth 180 number of trees :  0.9280494659921305
score decision hyperparameter balanced 35 features and 5 depth 190 number of trees :  0.9263631253513209
score decision hyperparameter balanced 35 features and 5 depth 200 number of trees :  0.9297358066329399
score decision hyperparameter balanced 35 features and 6 depth 110 number of trees :  0.9336706014614953
score decision hyperparameter balanced 35 features and 6 depth 120 number of trees :  0.9347948285553682
score decision hyperparameter balanced 35 features and 6 depth 130 number of trees :  0.9370432827431141
score decision hyperparameter balanced 35 features and 6 depth 140 number of trees :  0.9370432827431141
score decision hyperparameter balanced 35 features and 6 depth 150 number of trees :  0.9342327150084317
score decision hyperparameter balanced 35 features and 

score decision hyperparameter balanced 36 features and 7 depth 150 number of trees :  0.9421023046655425
score decision hyperparameter balanced 36 features and 7 depth 160 number of trees :  0.9437886453063519
score decision hyperparameter balanced 36 features and 7 depth 170 number of trees :  0.9421023046655425
score decision hyperparameter balanced 36 features and 7 depth 180 number of trees :  0.9432265317594154
score decision hyperparameter balanced 36 features and 7 depth 190 number of trees :  0.9421023046655425
score decision hyperparameter balanced 36 features and 7 depth 200 number of trees :  0.940415964024733
score decision hyperparameter balanced 36 features and 8 depth 110 number of trees :  0.9482855536818438
score decision hyperparameter balanced 36 features and 8 depth 120 number of trees :  0.9494097807757167
score decision hyperparameter balanced 36 features and 8 depth 130 number of trees :  0.9499718943226532
score decision hyperparameter balanced 36 features and 8

score decision hyperparameter balanced 37 features and 9 depth 130 number of trees :  0.9465992130410343
score decision hyperparameter balanced 37 features and 9 depth 140 number of trees :  0.9505340078695896
score decision hyperparameter balanced 37 features and 9 depth 150 number of trees :  0.9494097807757167
score decision hyperparameter balanced 37 features and 9 depth 160 number of trees :  0.9460370994940978
score decision hyperparameter balanced 37 features and 9 depth 170 number of trees :  0.9488476672287802
score decision hyperparameter balanced 37 features and 9 depth 180 number of trees :  0.9482855536818438
score decision hyperparameter balanced 37 features and 9 depth 190 number of trees :  0.9477234401349073
score decision hyperparameter balanced 37 features and 9 depth 200 number of trees :  0.9494097807757167
score decision hyperparameter balanced 37 features and 10 depth 110 number of trees :  0.9471613265879708
score decision hyperparameter balanced 37 features and

score decision hyperparameter balanced 39 features and 5 depth 110 number of trees :  0.9314221472737493
score decision hyperparameter balanced 39 features and 5 depth 120 number of trees :  0.9325463743676222
score decision hyperparameter balanced 39 features and 5 depth 130 number of trees :  0.9302979201798763
score decision hyperparameter balanced 39 features and 5 depth 140 number of trees :  0.9280494659921305
score decision hyperparameter balanced 39 features and 5 depth 150 number of trees :  0.9286115795390669
score decision hyperparameter balanced 39 features and 5 depth 160 number of trees :  0.9302979201798763
score decision hyperparameter balanced 39 features and 5 depth 170 number of trees :  0.9269252388982574
score decision hyperparameter balanced 39 features and 5 depth 180 number of trees :  0.9297358066329399
score decision hyperparameter balanced 39 features and 5 depth 190 number of trees :  0.925238898257448
score decision hyperparameter balanced 39 features and 5

score decision hyperparameter balanced 40 features and 6 depth 200 number of trees :  0.9370432827431141
score decision hyperparameter balanced 40 features and 7 depth 110 number of trees :  0.940415964024733
score decision hyperparameter balanced 40 features and 7 depth 120 number of trees :  0.9426644182124789
score decision hyperparameter balanced 40 features and 7 depth 130 number of trees :  0.9409780775716695
score decision hyperparameter balanced 40 features and 7 depth 140 number of trees :  0.9437886453063519
score decision hyperparameter balanced 40 features and 7 depth 150 number of trees :  0.9409780775716695
score decision hyperparameter balanced 40 features and 7 depth 160 number of trees :  0.938167509836987
score decision hyperparameter balanced 40 features and 7 depth 170 number of trees :  0.9409780775716695
score decision hyperparameter balanced 40 features and 7 depth 180 number of trees :  0.941540191118606
score decision hyperparameter balanced 40 features and 7 d

score decision hyperparameter balanced 41 features and 8 depth 190 number of trees :  0.9488476672287802
score decision hyperparameter balanced 41 features and 8 depth 200 number of trees :  0.9482855536818438
score decision hyperparameter balanced 41 features and 9 depth 110 number of trees :  0.9471613265879708
score decision hyperparameter balanced 41 features and 9 depth 120 number of trees :  0.9505340078695896
score decision hyperparameter balanced 41 features and 9 depth 130 number of trees :  0.9454749859471613
score decision hyperparameter balanced 41 features and 9 depth 140 number of trees :  0.9482855536818438
score decision hyperparameter balanced 41 features and 9 depth 150 number of trees :  0.9471613265879708
score decision hyperparameter balanced 41 features and 9 depth 160 number of trees :  0.9477234401349073
score decision hyperparameter balanced 41 features and 9 depth 170 number of trees :  0.9471613265879708
score decision hyperparameter balanced 41 features and 

score decision hyperparameter balanced 42 features and 10 depth 170 number of trees :  0.9432265317594154
score decision hyperparameter balanced 42 features and 10 depth 180 number of trees :  0.9432265317594154
score decision hyperparameter balanced 42 features and 10 depth 190 number of trees :  0.9465992130410343
score decision hyperparameter balanced 42 features and 10 depth 200 number of trees :  0.9488476672287802


ValueError: max_features must be in (0, n_features]

In [26]:
#k_fold cross validation IMU

#load dataset
dataset_import = pd.read_csv(r'/Users/danielsaffertmuller/Documents/Gesundheits- und Rehabilitationstechnik /Masterarbeit/Cereneo/dataprocessing/matlab_functions/Features_prod_IMU_v3.0.csv')
dataset = np.array(dataset_import)

#show shape of dataset
print(f'Shape of Dataset{dataset.shape}')



#show shape of features
x=dataset[:,:42]
print(f'Shape of Features{x.shape}')

#show shape of class
y=dataset[:,42]
print(f'Shape of class{y.shape}')
print(f'class{y}')


groups=dataset[:,43]
print(f'Shape of class{groups.shape}')
print(f'group{groups}')






from sklearn.model_selection import GroupKFold

clf = RandomForestClassifier(max_features=4,max_depth=10 , class_weight="balanced" , n_estimators=120)


gkf = GroupKFold(n_splits=8)
for train, test in gkf.split(x, y, groups=groups):
        x_train=x[train]
        y_train=y[train]
        print(x_train.shape)
        print(y_train.shape)
        
        clf.fit(x_train, y_train)
        
        y_pred=clf.predict(x[test])
        y_test=y[test]
        print(y_pred.shape)
        print(y_test.shape)
        
        score= clf.score(x[test], y[test])
        print(score)
        print(confusion_matrix(y_test, y_pred))
        print(classification_report(y_test, y_pred))

Shape of Dataset(2964, 44)
Shape of Features(2964, 42)
Shape of class(2964,)
class[1. 1. 1. ... 4. 4. 4.]
Shape of class(2964,)
group[1. 1. 1. ... 8. 8. 8.]
(2532, 42)
(2532,)
(432,)
(432,)
0.7777777777777778
[[117   1   0   0]
 [  5 114   0   0]
 [  0   0 100   0]
 [  6   2  82   5]]
              precision    recall  f1-score   support

         1.0       0.91      0.99      0.95       118
         2.0       0.97      0.96      0.97       119
         3.0       0.55      1.00      0.71       100
         4.0       1.00      0.05      0.10        95

    accuracy                           0.78       432
   macro avg       0.86      0.75      0.68       432
weighted avg       0.87      0.78      0.71       432

(2536, 42)
(2536,)
(428,)
(428,)
0.8714953271028038
[[103  19   0   0]
 [  0 119   2   0]
 [  0  14 151  20]
 [  0   0   0   0]]
              precision    recall  f1-score   support

         1.0       1.00      0.84      0.92       122
         2.0       0.78      0.98      0.

/Users/danielsaffertmuller/opt/anaconda3/lib/python3.8/site-packages/sklearn/metrics/_classification.py:1221: UndefinedMetricWarning: Recall and F-score are ill-defined and being set to 0.0 in labels with no true samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))


(416,)
(416,)
0.8629807692307693
[[ 87  27   4   0]
 [  1 117   0   0]
 [  0   1 135   1]
 [  0   0  23  20]]
              precision    recall  f1-score   support

         1.0       0.99      0.74      0.84       118
         2.0       0.81      0.99      0.89       118
         3.0       0.83      0.99      0.90       137
         4.0       0.95      0.47      0.62        43

    accuracy                           0.86       416
   macro avg       0.90      0.79      0.82       416
weighted avg       0.88      0.86      0.85       416

(2581, 42)
(2581,)
(383,)
(383,)
0.9321148825065274
[[120   6   2   4]
 [  4 105  10   0]
 [  0   0 132   0]
 [  0   0   0   0]]
              precision    recall  f1-score   support

         1.0       0.97      0.91      0.94       132
         2.0       0.95      0.88      0.91       119
         3.0       0.92      1.00      0.96       132
         4.0       0.00      0.00      0.00         0

    accuracy                           0.93       383


/Users/danielsaffertmuller/opt/anaconda3/lib/python3.8/site-packages/sklearn/metrics/_classification.py:1221: UndefinedMetricWarning: Recall and F-score are ill-defined and being set to 0.0 in labels with no true samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))


(340,)
(340,)
0.5617647058823529
[[117   0   0   0]
 [118   0   0   0]
 [ 10   0  74   0]
 [  0   0  21   0]]
              precision    recall  f1-score   support

         1.0       0.48      1.00      0.65       117
         2.0       0.00      0.00      0.00       118
         3.0       0.78      0.88      0.83        84
         4.0       0.00      0.00      0.00        21

    accuracy                           0.56       340
   macro avg       0.31      0.47      0.37       340
weighted avg       0.36      0.56      0.43       340

(2629, 42)
(2629,)


/Users/danielsaffertmuller/opt/anaconda3/lib/python3.8/site-packages/sklearn/metrics/_classification.py:1221: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))


(335,)
(335,)
0.8328358208955224
[[ 56   2   1   2]
 [  0 120   0   0]
 [  0   0 103   0]
 [  0   0  51   0]]
              precision    recall  f1-score   support

         1.0       1.00      0.92      0.96        61
         2.0       0.98      1.00      0.99       120
         3.0       0.66      1.00      0.80       103
         4.0       0.00      0.00      0.00        51

    accuracy                           0.83       335
   macro avg       0.66      0.73      0.69       335
weighted avg       0.74      0.83      0.78       335

(2633, 42)
(2633,)
(331,)
(331,)
0.49244712990936557
[[119   0   0   0]
 [117   0   0   1]
 [  0   0   4  48]
 [  0   0   2  40]]
              precision    recall  f1-score   support

         1.0       0.50      1.00      0.67       119
         2.0       0.00      0.00      0.00       118
         3.0       0.67      0.08      0.14        52
         4.0       0.45      0.95      0.61        42

    accuracy                           0.49       331

/Users/danielsaffertmuller/opt/anaconda3/lib/python3.8/site-packages/sklearn/metrics/_classification.py:1221: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))


(299,)
(299,)
0.7658862876254181
[[ 53  65   0   1]
 [  0 118   0   0]
 [  0   1  58   3]
 [  0   0   0   0]]
              precision    recall  f1-score   support

         1.0       1.00      0.45      0.62       119
         2.0       0.64      1.00      0.78       118
         3.0       1.00      0.94      0.97        62
         4.0       0.00      0.00      0.00         0

    accuracy                           0.77       299
   macro avg       0.66      0.60      0.59       299
weighted avg       0.86      0.77      0.75       299



/Users/danielsaffertmuller/opt/anaconda3/lib/python3.8/site-packages/sklearn/metrics/_classification.py:1221: UndefinedMetricWarning: Recall and F-score are ill-defined and being set to 0.0 in labels with no true samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
