In [59]:
#script for masterthesis 

import numpy as np
import pandas as pd
from sklearn.tree import DecisionTreeClassifier
from sklearn.ensemble import RandomForestClassifier
from sklearn.neighbors import KNeighborsClassifier


from sklearn.feature_selection import VarianceThreshold
from sklearn.model_selection import GridSearchCV
from sklearn.model_selection import train_test_split
from sklearn.metrics import confusion_matrix
from sklearn.model_selection import GroupKFold
from sklearn.metrics import classification_report





In [60]:
#load dataset
dataset_import = pd.read_csv(r'/Users/danielsaffertmuller/Documents/Gesundheits- und Rehabilitationstechnik /Masterarbeit/Cereneo/dataprocessing/matlab_functions/Features_prod_v3.0.csv')
dataset = np.array(dataset_import)

In [61]:
#show shape of dataset
print(f'Shape of Dataset{dataset.shape}')

Shape of Dataset(2811, 44)


In [62]:
#show shape of features
x=dataset[:,:42]
print(f'Shape of Features{x.shape}')

Shape of Features(2811, 42)


In [63]:
#show shape of class
y=dataset[:,42]
print(f'Shape of class{y.shape}')
print(f'class{y}')

Shape of class(2811,)
class[1. 1. 1. ... 4. 4. 4.]


In [65]:
#tain and test data split
x_train, x_test, y_train, y_test =train_test_split(x,y,test_size=0.3) 

In [66]:
##random forest hyper paramerter tuning
class_weight = ["balanced", "balanced_subsample"]
n_trees = [10, 20, 30, 40 , 50, 60, 70, 80, 90, 100, 110, 120, 130, 140, 150, 160, 170, 180, 190, 200]
for i in range(1,57):
    for j in range(5,11):
        for k in range (0,1):
             for p in range (10,20):
                clf = RandomForestClassifier(max_features=i,max_depth=j,class_weight=class_weight[k], n_estimators=n_trees[p])
                clf.fit(x_train, y_train)
                score= clf.score(x_test, y_test)
                y_pred=clf.predict(x_test)
              
                print(f'score decision hyperparameter {class_weight[k]} {i} features and {j} depth {n_trees[p]} number of trees :  {score}')

    

score decision hyperparameter balanced 1 features and 5 depth 110 number of trees :  0.9620853080568721
score decision hyperparameter balanced 1 features and 5 depth 120 number of trees :  0.9656398104265402
score decision hyperparameter balanced 1 features and 5 depth 130 number of trees :  0.957345971563981
score decision hyperparameter balanced 1 features and 5 depth 140 number of trees :  0.9585308056872038
score decision hyperparameter balanced 1 features and 5 depth 150 number of trees :  0.9609004739336493
score decision hyperparameter balanced 1 features and 5 depth 160 number of trees :  0.9609004739336493
score decision hyperparameter balanced 1 features and 5 depth 170 number of trees :  0.9632701421800948
score decision hyperparameter balanced 1 features and 5 depth 180 number of trees :  0.9620853080568721
score decision hyperparameter balanced 1 features and 5 depth 190 number of trees :  0.9620853080568721
score decision hyperparameter balanced 1 features and 5 depth 200

score decision hyperparameter balanced 2 features and 6 depth 200 number of trees :  0.9774881516587678
score decision hyperparameter balanced 2 features and 7 depth 110 number of trees :  0.9822274881516587
score decision hyperparameter balanced 2 features and 7 depth 120 number of trees :  0.9786729857819905
score decision hyperparameter balanced 2 features and 7 depth 130 number of trees :  0.9774881516587678
score decision hyperparameter balanced 2 features and 7 depth 140 number of trees :  0.9786729857819905
score decision hyperparameter balanced 2 features and 7 depth 150 number of trees :  0.9774881516587678
score decision hyperparameter balanced 2 features and 7 depth 160 number of trees :  0.9786729857819905
score decision hyperparameter balanced 2 features and 7 depth 170 number of trees :  0.9774881516587678
score decision hyperparameter balanced 2 features and 7 depth 180 number of trees :  0.9774881516587678
score decision hyperparameter balanced 2 features and 7 depth 19

score decision hyperparameter balanced 3 features and 8 depth 190 number of trees :  0.981042654028436
score decision hyperparameter balanced 3 features and 8 depth 200 number of trees :  0.9798578199052133
score decision hyperparameter balanced 3 features and 9 depth 110 number of trees :  0.9786729857819905
score decision hyperparameter balanced 3 features and 9 depth 120 number of trees :  0.9834123222748815
score decision hyperparameter balanced 3 features and 9 depth 130 number of trees :  0.981042654028436
score decision hyperparameter balanced 3 features and 9 depth 140 number of trees :  0.981042654028436
score decision hyperparameter balanced 3 features and 9 depth 150 number of trees :  0.9845971563981043
score decision hyperparameter balanced 3 features and 9 depth 160 number of trees :  0.9834123222748815
score decision hyperparameter balanced 3 features and 9 depth 170 number of trees :  0.9822274881516587
score decision hyperparameter balanced 3 features and 9 depth 180 n

score decision hyperparameter balanced 4 features and 10 depth 180 number of trees :  0.9834123222748815
score decision hyperparameter balanced 4 features and 10 depth 190 number of trees :  0.9834123222748815
score decision hyperparameter balanced 4 features and 10 depth 200 number of trees :  0.9834123222748815
score decision hyperparameter balanced 5 features and 5 depth 110 number of trees :  0.9656398104265402
score decision hyperparameter balanced 5 features and 5 depth 120 number of trees :  0.9680094786729858
score decision hyperparameter balanced 5 features and 5 depth 130 number of trees :  0.966824644549763
score decision hyperparameter balanced 5 features and 5 depth 140 number of trees :  0.9691943127962085
score decision hyperparameter balanced 5 features and 5 depth 150 number of trees :  0.9656398104265402
score decision hyperparameter balanced 5 features and 5 depth 160 number of trees :  0.9680094786729858
score decision hyperparameter balanced 5 features and 5 depth 

score decision hyperparameter balanced 6 features and 6 depth 170 number of trees :  0.9774881516587678
score decision hyperparameter balanced 6 features and 6 depth 180 number of trees :  0.9751184834123223
score decision hyperparameter balanced 6 features and 6 depth 190 number of trees :  0.9751184834123223
score decision hyperparameter balanced 6 features and 6 depth 200 number of trees :  0.976303317535545
score decision hyperparameter balanced 6 features and 7 depth 110 number of trees :  0.9798578199052133
score decision hyperparameter balanced 6 features and 7 depth 120 number of trees :  0.9786729857819905
score decision hyperparameter balanced 6 features and 7 depth 130 number of trees :  0.9774881516587678
score decision hyperparameter balanced 6 features and 7 depth 140 number of trees :  0.976303317535545
score decision hyperparameter balanced 6 features and 7 depth 150 number of trees :  0.9786729857819905
score decision hyperparameter balanced 6 features and 7 depth 160 

score decision hyperparameter balanced 7 features and 8 depth 160 number of trees :  0.9845971563981043
score decision hyperparameter balanced 7 features and 8 depth 170 number of trees :  0.9822274881516587
score decision hyperparameter balanced 7 features and 8 depth 180 number of trees :  0.9822274881516587
score decision hyperparameter balanced 7 features and 8 depth 190 number of trees :  0.981042654028436
score decision hyperparameter balanced 7 features and 8 depth 200 number of trees :  0.9822274881516587
score decision hyperparameter balanced 7 features and 9 depth 110 number of trees :  0.9822274881516587
score decision hyperparameter balanced 7 features and 9 depth 120 number of trees :  0.9834123222748815
score decision hyperparameter balanced 7 features and 9 depth 130 number of trees :  0.9834123222748815
score decision hyperparameter balanced 7 features and 9 depth 140 number of trees :  0.9834123222748815
score decision hyperparameter balanced 7 features and 9 depth 150

score decision hyperparameter balanced 8 features and 10 depth 150 number of trees :  0.9845971563981043
score decision hyperparameter balanced 8 features and 10 depth 160 number of trees :  0.9822274881516587
score decision hyperparameter balanced 8 features and 10 depth 170 number of trees :  0.985781990521327
score decision hyperparameter balanced 8 features and 10 depth 180 number of trees :  0.9845971563981043
score decision hyperparameter balanced 8 features and 10 depth 190 number of trees :  0.9834123222748815
score decision hyperparameter balanced 8 features and 10 depth 200 number of trees :  0.9822274881516587
score decision hyperparameter balanced 9 features and 5 depth 110 number of trees :  0.966824644549763
score decision hyperparameter balanced 9 features and 5 depth 120 number of trees :  0.9644549763033176
score decision hyperparameter balanced 9 features and 5 depth 130 number of trees :  0.9620853080568721
score decision hyperparameter balanced 9 features and 5 dept

score decision hyperparameter balanced 10 features and 6 depth 140 number of trees :  0.9739336492890995
score decision hyperparameter balanced 10 features and 6 depth 150 number of trees :  0.9739336492890995
score decision hyperparameter balanced 10 features and 6 depth 160 number of trees :  0.9786729857819905
score decision hyperparameter balanced 10 features and 6 depth 170 number of trees :  0.9739336492890995
score decision hyperparameter balanced 10 features and 6 depth 180 number of trees :  0.9727488151658767
score decision hyperparameter balanced 10 features and 6 depth 190 number of trees :  0.9798578199052133
score decision hyperparameter balanced 10 features and 6 depth 200 number of trees :  0.9739336492890995
score decision hyperparameter balanced 10 features and 7 depth 110 number of trees :  0.976303317535545
score decision hyperparameter balanced 10 features and 7 depth 120 number of trees :  0.9786729857819905
score decision hyperparameter balanced 10 features and 7

score decision hyperparameter balanced 11 features and 8 depth 130 number of trees :  0.9834123222748815
score decision hyperparameter balanced 11 features and 8 depth 140 number of trees :  0.9798578199052133
score decision hyperparameter balanced 11 features and 8 depth 150 number of trees :  0.9822274881516587
score decision hyperparameter balanced 11 features and 8 depth 160 number of trees :  0.981042654028436
score decision hyperparameter balanced 11 features and 8 depth 170 number of trees :  0.9822274881516587
score decision hyperparameter balanced 11 features and 8 depth 180 number of trees :  0.9822274881516587
score decision hyperparameter balanced 11 features and 8 depth 190 number of trees :  0.981042654028436
score decision hyperparameter balanced 11 features and 8 depth 200 number of trees :  0.9822274881516587
score decision hyperparameter balanced 11 features and 9 depth 110 number of trees :  0.9822274881516587
score decision hyperparameter balanced 11 features and 9 

score decision hyperparameter balanced 12 features and 10 depth 120 number of trees :  0.9834123222748815
score decision hyperparameter balanced 12 features and 10 depth 130 number of trees :  0.9822274881516587
score decision hyperparameter balanced 12 features and 10 depth 140 number of trees :  0.9834123222748815
score decision hyperparameter balanced 12 features and 10 depth 150 number of trees :  0.9822274881516587
score decision hyperparameter balanced 12 features and 10 depth 160 number of trees :  0.9845971563981043
score decision hyperparameter balanced 12 features and 10 depth 170 number of trees :  0.981042654028436
score decision hyperparameter balanced 12 features and 10 depth 180 number of trees :  0.9822274881516587
score decision hyperparameter balanced 12 features and 10 depth 190 number of trees :  0.985781990521327
score decision hyperparameter balanced 12 features and 10 depth 200 number of trees :  0.9834123222748815
score decision hyperparameter balanced 13 featur

score decision hyperparameter balanced 14 features and 6 depth 110 number of trees :  0.9751184834123223
score decision hyperparameter balanced 14 features and 6 depth 120 number of trees :  0.9715639810426541
score decision hyperparameter balanced 14 features and 6 depth 130 number of trees :  0.9751184834123223
score decision hyperparameter balanced 14 features and 6 depth 140 number of trees :  0.976303317535545
score decision hyperparameter balanced 14 features and 6 depth 150 number of trees :  0.9727488151658767
score decision hyperparameter balanced 14 features and 6 depth 160 number of trees :  0.9727488151658767
score decision hyperparameter balanced 14 features and 6 depth 170 number of trees :  0.9739336492890995
score decision hyperparameter balanced 14 features and 6 depth 180 number of trees :  0.9739336492890995
score decision hyperparameter balanced 14 features and 6 depth 190 number of trees :  0.976303317535545
score decision hyperparameter balanced 14 features and 6 

score decision hyperparameter balanced 15 features and 7 depth 200 number of trees :  0.9798578199052133
score decision hyperparameter balanced 15 features and 8 depth 110 number of trees :  0.9822274881516587
score decision hyperparameter balanced 15 features and 8 depth 120 number of trees :  0.981042654028436
score decision hyperparameter balanced 15 features and 8 depth 130 number of trees :  0.9822274881516587
score decision hyperparameter balanced 15 features and 8 depth 140 number of trees :  0.9822274881516587
score decision hyperparameter balanced 15 features and 8 depth 150 number of trees :  0.9822274881516587
score decision hyperparameter balanced 15 features and 8 depth 160 number of trees :  0.981042654028436
score decision hyperparameter balanced 15 features and 8 depth 170 number of trees :  0.9786729857819905
score decision hyperparameter balanced 15 features and 8 depth 180 number of trees :  0.9822274881516587
score decision hyperparameter balanced 15 features and 8 

score decision hyperparameter balanced 16 features and 9 depth 190 number of trees :  0.981042654028436
score decision hyperparameter balanced 16 features and 9 depth 200 number of trees :  0.981042654028436
score decision hyperparameter balanced 16 features and 10 depth 110 number of trees :  0.981042654028436
score decision hyperparameter balanced 16 features and 10 depth 120 number of trees :  0.9822274881516587
score decision hyperparameter balanced 16 features and 10 depth 130 number of trees :  0.9822274881516587
score decision hyperparameter balanced 16 features and 10 depth 140 number of trees :  0.981042654028436
score decision hyperparameter balanced 16 features and 10 depth 150 number of trees :  0.9822274881516587
score decision hyperparameter balanced 16 features and 10 depth 160 number of trees :  0.9822274881516587
score decision hyperparameter balanced 16 features and 10 depth 170 number of trees :  0.981042654028436
score decision hyperparameter balanced 16 features an

score decision hyperparameter balanced 18 features and 5 depth 180 number of trees :  0.9644549763033176
score decision hyperparameter balanced 18 features and 5 depth 190 number of trees :  0.9656398104265402
score decision hyperparameter balanced 18 features and 5 depth 200 number of trees :  0.9644549763033176
score decision hyperparameter balanced 18 features and 6 depth 110 number of trees :  0.9727488151658767
score decision hyperparameter balanced 18 features and 6 depth 120 number of trees :  0.9739336492890995
score decision hyperparameter balanced 18 features and 6 depth 130 number of trees :  0.9715639810426541
score decision hyperparameter balanced 18 features and 6 depth 140 number of trees :  0.9727488151658767
score decision hyperparameter balanced 18 features and 6 depth 150 number of trees :  0.9739336492890995
score decision hyperparameter balanced 18 features and 6 depth 160 number of trees :  0.9691943127962085
score decision hyperparameter balanced 18 features and 

score decision hyperparameter balanced 19 features and 7 depth 170 number of trees :  0.981042654028436
score decision hyperparameter balanced 19 features and 7 depth 180 number of trees :  0.9786729857819905
score decision hyperparameter balanced 19 features and 7 depth 190 number of trees :  0.9798578199052133
score decision hyperparameter balanced 19 features and 7 depth 200 number of trees :  0.9774881516587678
score decision hyperparameter balanced 19 features and 8 depth 110 number of trees :  0.981042654028436
score decision hyperparameter balanced 19 features and 8 depth 120 number of trees :  0.9774881516587678
score decision hyperparameter balanced 19 features and 8 depth 130 number of trees :  0.9822274881516587
score decision hyperparameter balanced 19 features and 8 depth 140 number of trees :  0.981042654028436
score decision hyperparameter balanced 19 features and 8 depth 150 number of trees :  0.981042654028436
score decision hyperparameter balanced 19 features and 8 de

score decision hyperparameter balanced 20 features and 9 depth 160 number of trees :  0.981042654028436
score decision hyperparameter balanced 20 features and 9 depth 170 number of trees :  0.9822274881516587
score decision hyperparameter balanced 20 features and 9 depth 180 number of trees :  0.9798578199052133
score decision hyperparameter balanced 20 features and 9 depth 190 number of trees :  0.9798578199052133
score decision hyperparameter balanced 20 features and 9 depth 200 number of trees :  0.981042654028436
score decision hyperparameter balanced 20 features and 10 depth 110 number of trees :  0.9798578199052133
score decision hyperparameter balanced 20 features and 10 depth 120 number of trees :  0.981042654028436
score decision hyperparameter balanced 20 features and 10 depth 130 number of trees :  0.9798578199052133
score decision hyperparameter balanced 20 features and 10 depth 140 number of trees :  0.981042654028436
score decision hyperparameter balanced 20 features and 

score decision hyperparameter balanced 22 features and 5 depth 140 number of trees :  0.9644549763033176
score decision hyperparameter balanced 22 features and 5 depth 150 number of trees :  0.9656398104265402
score decision hyperparameter balanced 22 features and 5 depth 160 number of trees :  0.9644549763033176
score decision hyperparameter balanced 22 features and 5 depth 170 number of trees :  0.9644549763033176
score decision hyperparameter balanced 22 features and 5 depth 180 number of trees :  0.9632701421800948
score decision hyperparameter balanced 22 features and 5 depth 190 number of trees :  0.9656398104265402
score decision hyperparameter balanced 22 features and 5 depth 200 number of trees :  0.9656398104265402
score decision hyperparameter balanced 22 features and 6 depth 110 number of trees :  0.9739336492890995
score decision hyperparameter balanced 22 features and 6 depth 120 number of trees :  0.9727488151658767
score decision hyperparameter balanced 22 features and 

score decision hyperparameter balanced 23 features and 7 depth 130 number of trees :  0.9798578199052133
score decision hyperparameter balanced 23 features and 7 depth 140 number of trees :  0.9798578199052133
score decision hyperparameter balanced 23 features and 7 depth 150 number of trees :  0.9786729857819905
score decision hyperparameter balanced 23 features and 7 depth 160 number of trees :  0.976303317535545
score decision hyperparameter balanced 23 features and 7 depth 170 number of trees :  0.9798578199052133
score decision hyperparameter balanced 23 features and 7 depth 180 number of trees :  0.9774881516587678
score decision hyperparameter balanced 23 features and 7 depth 190 number of trees :  0.9786729857819905
score decision hyperparameter balanced 23 features and 7 depth 200 number of trees :  0.9786729857819905
score decision hyperparameter balanced 23 features and 8 depth 110 number of trees :  0.9798578199052133
score decision hyperparameter balanced 23 features and 8

score decision hyperparameter balanced 24 features and 9 depth 120 number of trees :  0.981042654028436
score decision hyperparameter balanced 24 features and 9 depth 130 number of trees :  0.9798578199052133
score decision hyperparameter balanced 24 features and 9 depth 140 number of trees :  0.9786729857819905
score decision hyperparameter balanced 24 features and 9 depth 150 number of trees :  0.9786729857819905
score decision hyperparameter balanced 24 features and 9 depth 160 number of trees :  0.9798578199052133
score decision hyperparameter balanced 24 features and 9 depth 170 number of trees :  0.981042654028436
score decision hyperparameter balanced 24 features and 9 depth 180 number of trees :  0.981042654028436
score decision hyperparameter balanced 24 features and 9 depth 190 number of trees :  0.9786729857819905
score decision hyperparameter balanced 24 features and 9 depth 200 number of trees :  0.9786729857819905
score decision hyperparameter balanced 24 features and 10 

score decision hyperparameter balanced 26 features and 5 depth 110 number of trees :  0.9632701421800948
score decision hyperparameter balanced 26 features and 5 depth 120 number of trees :  0.9656398104265402
score decision hyperparameter balanced 26 features and 5 depth 130 number of trees :  0.9656398104265402
score decision hyperparameter balanced 26 features and 5 depth 140 number of trees :  0.9632701421800948
score decision hyperparameter balanced 26 features and 5 depth 150 number of trees :  0.9632701421800948
score decision hyperparameter balanced 26 features and 5 depth 160 number of trees :  0.9632701421800948
score decision hyperparameter balanced 26 features and 5 depth 170 number of trees :  0.9644549763033176
score decision hyperparameter balanced 26 features and 5 depth 180 number of trees :  0.9644549763033176
score decision hyperparameter balanced 26 features and 5 depth 190 number of trees :  0.9632701421800948
score decision hyperparameter balanced 26 features and 

score decision hyperparameter balanced 27 features and 6 depth 200 number of trees :  0.9739336492890995
score decision hyperparameter balanced 27 features and 7 depth 110 number of trees :  0.976303317535545
score decision hyperparameter balanced 27 features and 7 depth 120 number of trees :  0.9739336492890995
score decision hyperparameter balanced 27 features and 7 depth 130 number of trees :  0.9774881516587678
score decision hyperparameter balanced 27 features and 7 depth 140 number of trees :  0.976303317535545
score decision hyperparameter balanced 27 features and 7 depth 150 number of trees :  0.9774881516587678
score decision hyperparameter balanced 27 features and 7 depth 160 number of trees :  0.9798578199052133
score decision hyperparameter balanced 27 features and 7 depth 170 number of trees :  0.9751184834123223
score decision hyperparameter balanced 27 features and 7 depth 180 number of trees :  0.976303317535545
score decision hyperparameter balanced 27 features and 7 d

score decision hyperparameter balanced 28 features and 8 depth 190 number of trees :  0.9822274881516587
score decision hyperparameter balanced 28 features and 8 depth 200 number of trees :  0.9786729857819905
score decision hyperparameter balanced 28 features and 9 depth 110 number of trees :  0.9786729857819905
score decision hyperparameter balanced 28 features and 9 depth 120 number of trees :  0.9786729857819905
score decision hyperparameter balanced 28 features and 9 depth 130 number of trees :  0.9822274881516587
score decision hyperparameter balanced 28 features and 9 depth 140 number of trees :  0.981042654028436
score decision hyperparameter balanced 28 features and 9 depth 150 number of trees :  0.9786729857819905
score decision hyperparameter balanced 28 features and 9 depth 160 number of trees :  0.9798578199052133
score decision hyperparameter balanced 28 features and 9 depth 170 number of trees :  0.9786729857819905
score decision hyperparameter balanced 28 features and 9

score decision hyperparameter balanced 29 features and 10 depth 170 number of trees :  0.9774881516587678
score decision hyperparameter balanced 29 features and 10 depth 180 number of trees :  0.9774881516587678
score decision hyperparameter balanced 29 features and 10 depth 190 number of trees :  0.9774881516587678
score decision hyperparameter balanced 29 features and 10 depth 200 number of trees :  0.981042654028436
score decision hyperparameter balanced 30 features and 5 depth 110 number of trees :  0.9609004739336493
score decision hyperparameter balanced 30 features and 5 depth 120 number of trees :  0.9620853080568721
score decision hyperparameter balanced 30 features and 5 depth 130 number of trees :  0.9644549763033176
score decision hyperparameter balanced 30 features and 5 depth 140 number of trees :  0.9620853080568721
score decision hyperparameter balanced 30 features and 5 depth 150 number of trees :  0.9620853080568721
score decision hyperparameter balanced 30 features a

score decision hyperparameter balanced 31 features and 6 depth 160 number of trees :  0.9739336492890995
score decision hyperparameter balanced 31 features and 6 depth 170 number of trees :  0.9739336492890995
score decision hyperparameter balanced 31 features and 6 depth 180 number of trees :  0.9727488151658767
score decision hyperparameter balanced 31 features and 6 depth 190 number of trees :  0.9739336492890995
score decision hyperparameter balanced 31 features and 6 depth 200 number of trees :  0.9751184834123223
score decision hyperparameter balanced 31 features and 7 depth 110 number of trees :  0.9786729857819905
score decision hyperparameter balanced 31 features and 7 depth 120 number of trees :  0.9774881516587678
score decision hyperparameter balanced 31 features and 7 depth 130 number of trees :  0.976303317535545
score decision hyperparameter balanced 31 features and 7 depth 140 number of trees :  0.9751184834123223
score decision hyperparameter balanced 31 features and 7

score decision hyperparameter balanced 32 features and 8 depth 150 number of trees :  0.976303317535545
score decision hyperparameter balanced 32 features and 8 depth 160 number of trees :  0.9786729857819905
score decision hyperparameter balanced 32 features and 8 depth 170 number of trees :  0.9774881516587678
score decision hyperparameter balanced 32 features and 8 depth 180 number of trees :  0.9774881516587678
score decision hyperparameter balanced 32 features and 8 depth 190 number of trees :  0.976303317535545
score decision hyperparameter balanced 32 features and 8 depth 200 number of trees :  0.976303317535545
score decision hyperparameter balanced 32 features and 9 depth 110 number of trees :  0.9786729857819905
score decision hyperparameter balanced 32 features and 9 depth 120 number of trees :  0.9774881516587678
score decision hyperparameter balanced 32 features and 9 depth 130 number of trees :  0.976303317535545
score decision hyperparameter balanced 32 features and 9 de

score decision hyperparameter balanced 33 features and 10 depth 140 number of trees :  0.9786729857819905
score decision hyperparameter balanced 33 features and 10 depth 150 number of trees :  0.976303317535545
score decision hyperparameter balanced 33 features and 10 depth 160 number of trees :  0.9774881516587678
score decision hyperparameter balanced 33 features and 10 depth 170 number of trees :  0.9751184834123223
score decision hyperparameter balanced 33 features and 10 depth 180 number of trees :  0.976303317535545
score decision hyperparameter balanced 33 features and 10 depth 190 number of trees :  0.9786729857819905
score decision hyperparameter balanced 33 features and 10 depth 200 number of trees :  0.9774881516587678
score decision hyperparameter balanced 34 features and 5 depth 110 number of trees :  0.9620853080568721
score decision hyperparameter balanced 34 features and 5 depth 120 number of trees :  0.9620853080568721
score decision hyperparameter balanced 34 features

score decision hyperparameter balanced 35 features and 6 depth 130 number of trees :  0.9727488151658767
score decision hyperparameter balanced 35 features and 6 depth 140 number of trees :  0.9739336492890995
score decision hyperparameter balanced 35 features and 6 depth 150 number of trees :  0.9739336492890995
score decision hyperparameter balanced 35 features and 6 depth 160 number of trees :  0.9691943127962085
score decision hyperparameter balanced 35 features and 6 depth 170 number of trees :  0.9727488151658767
score decision hyperparameter balanced 35 features and 6 depth 180 number of trees :  0.9703791469194313
score decision hyperparameter balanced 35 features and 6 depth 190 number of trees :  0.9727488151658767
score decision hyperparameter balanced 35 features and 6 depth 200 number of trees :  0.9703791469194313
score decision hyperparameter balanced 35 features and 7 depth 110 number of trees :  0.9739336492890995
score decision hyperparameter balanced 35 features and 

score decision hyperparameter balanced 36 features and 8 depth 120 number of trees :  0.976303317535545
score decision hyperparameter balanced 36 features and 8 depth 130 number of trees :  0.976303317535545
score decision hyperparameter balanced 36 features and 8 depth 140 number of trees :  0.9774881516587678
score decision hyperparameter balanced 36 features and 8 depth 150 number of trees :  0.9774881516587678
score decision hyperparameter balanced 36 features and 8 depth 160 number of trees :  0.9751184834123223
score decision hyperparameter balanced 36 features and 8 depth 170 number of trees :  0.9751184834123223
score decision hyperparameter balanced 36 features and 8 depth 180 number of trees :  0.976303317535545
score decision hyperparameter balanced 36 features and 8 depth 190 number of trees :  0.976303317535545
score decision hyperparameter balanced 36 features and 8 depth 200 number of trees :  0.9751184834123223
score decision hyperparameter balanced 36 features and 9 de

score decision hyperparameter balanced 37 features and 10 depth 110 number of trees :  0.9715639810426541
score decision hyperparameter balanced 37 features and 10 depth 120 number of trees :  0.9786729857819905
score decision hyperparameter balanced 37 features and 10 depth 130 number of trees :  0.976303317535545
score decision hyperparameter balanced 37 features and 10 depth 140 number of trees :  0.9751184834123223
score decision hyperparameter balanced 37 features and 10 depth 150 number of trees :  0.9727488151658767
score decision hyperparameter balanced 37 features and 10 depth 160 number of trees :  0.9774881516587678
score decision hyperparameter balanced 37 features and 10 depth 170 number of trees :  0.9786729857819905
score decision hyperparameter balanced 37 features and 10 depth 180 number of trees :  0.976303317535545
score decision hyperparameter balanced 37 features and 10 depth 190 number of trees :  0.9751184834123223
score decision hyperparameter balanced 37 featur

score decision hyperparameter balanced 39 features and 5 depth 190 number of trees :  0.9644549763033176
score decision hyperparameter balanced 39 features and 5 depth 200 number of trees :  0.9620853080568721
score decision hyperparameter balanced 39 features and 6 depth 110 number of trees :  0.9680094786729858
score decision hyperparameter balanced 39 features and 6 depth 120 number of trees :  0.9680094786729858
score decision hyperparameter balanced 39 features and 6 depth 130 number of trees :  0.9703791469194313
score decision hyperparameter balanced 39 features and 6 depth 140 number of trees :  0.9715639810426541
score decision hyperparameter balanced 39 features and 6 depth 150 number of trees :  0.9703791469194313
score decision hyperparameter balanced 39 features and 6 depth 160 number of trees :  0.9715639810426541
score decision hyperparameter balanced 39 features and 6 depth 170 number of trees :  0.9691943127962085
score decision hyperparameter balanced 39 features and 

score decision hyperparameter balanced 40 features and 7 depth 180 number of trees :  0.9739336492890995
score decision hyperparameter balanced 40 features and 7 depth 190 number of trees :  0.9751184834123223
score decision hyperparameter balanced 40 features and 7 depth 200 number of trees :  0.9739336492890995
score decision hyperparameter balanced 40 features and 8 depth 110 number of trees :  0.9751184834123223
score decision hyperparameter balanced 40 features and 8 depth 120 number of trees :  0.9774881516587678
score decision hyperparameter balanced 40 features and 8 depth 130 number of trees :  0.976303317535545
score decision hyperparameter balanced 40 features and 8 depth 140 number of trees :  0.976303317535545
score decision hyperparameter balanced 40 features and 8 depth 150 number of trees :  0.9751184834123223
score decision hyperparameter balanced 40 features and 8 depth 160 number of trees :  0.9751184834123223
score decision hyperparameter balanced 40 features and 8 

score decision hyperparameter balanced 41 features and 9 depth 170 number of trees :  0.9751184834123223
score decision hyperparameter balanced 41 features and 9 depth 180 number of trees :  0.976303317535545
score decision hyperparameter balanced 41 features and 9 depth 190 number of trees :  0.9739336492890995
score decision hyperparameter balanced 41 features and 9 depth 200 number of trees :  0.9774881516587678
score decision hyperparameter balanced 41 features and 10 depth 110 number of trees :  0.976303317535545
score decision hyperparameter balanced 41 features and 10 depth 120 number of trees :  0.9739336492890995
score decision hyperparameter balanced 41 features and 10 depth 130 number of trees :  0.9774881516587678
score decision hyperparameter balanced 41 features and 10 depth 140 number of trees :  0.9751184834123223
score decision hyperparameter balanced 41 features and 10 depth 150 number of trees :  0.976303317535545
score decision hyperparameter balanced 41 features an

ValueError: max_features must be in (0, n_features]

In [ ]:
###determine hyperparmeters with GridSearchCV

from sklearn import datasets
from sklearn.model_selection import train_test_split
from sklearn.model_selection import GridSearchCV
from sklearn.metrics import classification_report


#load dataset
dataset_import = pd.read_csv(r'/Users/danielsaffertmuller/Documents/Gesundheits- und Rehabilitationstechnik /Masterarbeit/Cereneo/dataprocessing/matlab_functions/Features_prod.csv')
dataset = np.array(dataset_import)

#show shape of dataset
print(f'Shape of Dataset{dataset.shape}')



#show shape of features
x=dataset[:,:56]
print(f'Shape of Features{x.shape}')

#show shape of class
y=dataset[:,56]
print(f'Shape of class{y.shape}')
print(f'class{y}')


groups=dataset[:,57]
print(f'Shape of class{groups.shape}')
print(f'group{groups}')



# Split the dataset in two equal parts
X_train, X_test, y_train, y_test = train_test_split(x, y, test_size=0.5, random_state=0)

# Set the parameters by cross-validation
tuned_parameters = [
    {"max_features": [1,20],
     "max_depth": [1,10],
     "class_weight": ["balanced", "balanced_subsample"],
     "n_estimators": [50, 60, 70, 80, 90, 100, 110, 120, 130, 140, 150, 160, 170, 180, 190, 200]}
    
]


scores = ["precision", "recall"]

for score in scores:
    print("# Tuning hyper-parameters for %s" % score)
    print()

    clf = GridSearchCV(RandomForestClassifier(), tuned_parameters, scoring="%s_macro" % score)
    clf.fit(X_train, y_train)

    print("Best parameters set found on development set:")
    print()
    print(clf.best_params_)
    print()
    print("Grid scores on development set:")
    print()
    means = clf.cv_results_["mean_test_score"]
    stds = clf.cv_results_["std_test_score"]
    for mean, std, params in zip(means, stds, clf.cv_results_["params"]):
        print("%0.3f (+/-%0.03f) for %r" % (mean, std * 2, params))
    print()

    print("Detailed classification report:")
    print()
    print("The model is trained on the full development set.")
    print("The scores are computed on the full evaluation set.")
    print()
    y_true, y_pred = y_test, clf.predict(X_test)
    print(classification_report(y_true, y_pred))
    print()

In [67]:
#k_fold cross validation

#load dataset
dataset_import = pd.read_csv(r'/Users/danielsaffertmuller/Documents/Gesundheits- und Rehabilitationstechnik /Masterarbeit/Cereneo/dataprocessing/matlab_functions/Features_prod_v2.1.csv')
dataset = np.array(dataset_import)

#show shape of dataset
print(f'Shape of Dataset{dataset.shape}')



#show shape of features
x=dataset[:,:42]
print(f'Shape of Features{x.shape}')

#show shape of class
y=dataset[:,42]
print(f'Shape of class{y.shape}')
print(f'class{y}')


groups=dataset[:,43]
print(f'Shape of class{groups.shape}')
print(f'group{groups}')




from sklearn.model_selection import GroupKFold

clf = RandomForestClassifier(class_weight= "balanced",max_features= 4, max_depth=9, n_estimators= 200)


gkf = GroupKFold(n_splits=8)
for train, test in gkf.split(x, y, groups=groups):
        x_train=x[train]
        y_train=y[train]
        print(x_train.shape)
        print(y_train.shape)
        
        clf.fit(x_train, y_train)
        
        y_pred=clf.predict(x[test])
        y_test=y[test]
        print(y_pred.shape)
        print(y_test.shape)
        
        score= clf.score(x[test], y[test])
        print(score)
        print(confusion_matrix(y_test, y_pred))
        print(classification_report(y_test, y_pred))
        


Shape of Dataset(2730, 44)
Shape of Features(2730, 42)
Shape of class(2730,)
class[1. 1. 1. ... 4. 4. 4.]
Shape of class(2730,)
group[1. 1. 1. ... 8. 8. 8.]
(2344, 42)
(2344,)
(386,)
(386,)
0.7875647668393783
[[ 80  38   0   0]
 [  0 118   0   0]
 [  0   0 103   0]
 [  0   0  44   3]]
              precision    recall  f1-score   support

         1.0       1.00      0.68      0.81       118
         2.0       0.76      1.00      0.86       118
         3.0       0.70      1.00      0.82       103
         4.0       1.00      0.06      0.12        47

    accuracy                           0.79       386
   macro avg       0.86      0.69      0.65       386
weighted avg       0.85      0.79      0.74       386

(2349, 42)
(2349,)
(381,)
(381,)
0.9081364829396326
[[131   0   0   0]
 [  8 111   0   0]
 [  0  26 104   1]
 [  0   0   0   0]]
              precision    recall  f1-score   support

         1.0       0.94      1.00      0.97       131
         2.0       0.81      0.93      0.

/Users/danielsaffertmuller/opt/anaconda3/lib/python3.8/site-packages/sklearn/metrics/_classification.py:1221: UndefinedMetricWarning: Recall and F-score are ill-defined and being set to 0.0 in labels with no true samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))


(360,)
(360,)
1.0
[[117   0   0]
 [  0 120   0]
 [  0   0 123]]
              precision    recall  f1-score   support

         1.0       1.00      1.00      1.00       117
         2.0       1.00      1.00      1.00       120
         3.0       1.00      1.00      1.00       123

    accuracy                           1.00       360
   macro avg       1.00      1.00      1.00       360
weighted avg       1.00      1.00      1.00       360

(2384, 42)
(2384,)
(346,)
(346,)
0.9508670520231214
[[115   0   0   0]
 [  0  67   3   0]
 [  0   0 114  13]
 [  0   0   1  33]]
              precision    recall  f1-score   support

         1.0       1.00      1.00      1.00       115
         2.0       1.00      0.96      0.98        70
         3.0       0.97      0.90      0.93       127
         4.0       0.72      0.97      0.82        34

    accuracy                           0.95       346
   macro avg       0.92      0.96      0.93       346
weighted avg       0.96      0.95      0.95   

/Users/danielsaffertmuller/opt/anaconda3/lib/python3.8/site-packages/sklearn/metrics/_classification.py:1221: UndefinedMetricWarning: Recall and F-score are ill-defined and being set to 0.0 in labels with no true samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
